{
 "title": "ChRIS Dashboard",
 "time": { "from": "2023-12-14T23:58:13.266Z", "to": "2023-12-15T00:50:47.248Z" },
 "templating": {
  "list": [
   {
    "name": "ChRIS_Plugin_Image",
    "label": "ChRIS Plugin Image",
    "query": "SELECT DISTINCT\n  dock_image\nFROM\n  plugins_plugin\nLIMIT\n  50"
   },
   {
    "name": "PluginPod",
    "query": "SELECT\n  plugininstances_plugininstance.id\nFROM plugininstances_plugininstance\nWHERE plugininstances_plugininstance.start_date BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY plugininstances_plugininstance.start_date DESC\nLIMIT 50"
   }
  ]
 },
 "panels": [
  { "title": "Plugin Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average CPU, Memory Use, and Runtime by ChRIS Plugin Image Type(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (image) (   pod:container_cpu_usage:sum{}   * on(namespace, pod) group_right(image) kube_pod_container_info{image=~\"$ChRIS_Plugin_Image\"} )",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{image=~\"$ChRIS_Plugin_Image\"})",
     "legendFormat": "Memory Usage (Working Set)"
    },
    {
     "expr": "avg by (image) (last_over_time(timestamp((kube_pod_start_time{}   * on(namespace, pod) group_right(image) kube_pod_container_info{image_spec=~\"$ChRIS_Plugin_Image\"}))[1w:]) -    (kube_pod_start_time{}   * on(namespace, pod) group_right(image) kube_pod_container_info{image_spec=~\"$ChRIS_Plugin_Image\"}))",
     "legendFormat": "Runtime"
    }
   ]
  },
  {
   "title": "Number of ChRIS Plugin Image Type(s) Plugins Ran",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (image) (   kube_pod_container_info{image=~\"$ChRIS_Plugin_Image\"} ) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Plugins Running by Image Type (All)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (image) (\n  kube_pod_container_info{image=~\".+fnndsc.+\", image!~\"ghcr.io/fnndsc/pfcon.+\", image!~\"ghcr.io/fnndsc/pman.+\", image!~\"ghcr.io/fnndsc/cube.+\", image!~\"ghcr.io/fnndsc/aiochris.+\"}\n) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent Plugin Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n\tplugins_plugin.dock_image,\n\tplugininstances_plugininstance.error_code, \n\tplugininstances_plugininstance.feed_id AS \"Feed id\",\n\tplugininstances_plugininstance.id AS \"Plugin id\",\n\tplugininstances_plugininstance.previous_id AS \"Previous id\",\n\tplugininstances_plugininstance.status AS \"Status\",\n\tauth_user.username AS \"User\",\n\tplugins_computeresource.name AS \"Compute Resource\",\n\tplugininstances_plugininstance.start_date AS \"Start Date\",\n\tplugininstances_plugininstance.end_date AS \"End Date\",\n\tplugininstances_plugininstance.summary AS \"Summary\"\n\t\nFROM plugininstances_plugininstance\nINNER JOIN plugins_computeresource ON plugins_computeresource.id = plugininstances_plugininstance.compute_resource_id\nINNER JOIN auth_user ON auth_user.id = plugininstances_plugininstance.owner_id\nINNER JOIN plugins_plugin ON plugins_plugin.id = plugininstances_plugininstance.plugin_id\nWHERE plugininstances_plugininstance.error_code != ''\nORDER BY plugininstances_plugininstance.end_date DESC\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Number of Plugins Being Run by User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  generate_series(\n    DATE_TRUNC('minutes', plugininstances_plugininstance.start_date), \n    DATE_TRUNC(\n      'minutes', \n      CASE WHEN plugininstances_plugininstance.status = 'started' THEN now()\n      ELSE plugininstances_plugininstance.end_date\n      END\n    ), \n    '30 seconds'\n  ) as time_interval,\n  auth_user.username,\n  COUNT(*)\nFROM plugininstances_plugininstance\nINNER JOIN auth_user ON auth_user.id = plugininstances_plugininstance.owner_id\nWHERE status != 'cancelled' AND\nplugininstances_plugininstance.end_date BETWEEN '${__from:date:iso}' AND '${__to:date:iso}' OR\nplugininstances_plugininstance.end_date IS NULL\nGROUP BY time_interval, auth_user.username\nORDER BY time_interval DESC, auth_user.username;\n"
    }
   ]
  },
  {
   "title": "Plugins Ran in Grafana Time Range",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  auth_user.username \"Username\",\n  plugins_plugin.dock_image AS \"Plugin Image\",\n  plugininstances_plugininstance.id AS \"Plugin id\",\n  plugininstances_plugininstance.previous_id AS \"Previous id\",\n  plugininstances_plugininstance.start_date AS \"Start date\"\nFROM plugininstances_plugininstance\nINNER JOIN auth_user ON auth_user.id = plugininstances_plugininstance.owner_id\nINNER JOIN plugins_plugin ON plugins_plugin.id = plugininstances_plugininstance.plugin_id\nWHERE plugininstances_plugininstance.start_date BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY plugininstances_plugininstance.start_date DESC\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Average CPU, Memory Use, and Runtime by Pod Number Input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (pod) (pod:container_cpu_usage:sum{pod=~\"chris-jid-$PluginPod.+\"})",
     "legendFormat": "{{pod}} CPU Usage"
    },
    {
     "expr": "sum (   container_memory_working_set_bytes{pod=~\"chris-jid-$PluginPod.+\"} ) by(pod)",
     "legendFormat": "Memory Usage (Working Set)"
    },
    {
     "expr": "avg by (pod) (last_over_time(timestamp(kube_pod_start_time{namespace=\"hosting-of-medical-image-analysis-platform-a88466\", pod=~\"chris-jid-$PluginPod.+\"})[1w:]) - kube_pod_start_time{namespace=\"hosting-of-medical-image-analysis-platform-a88466\", pod=~\"chris-jid-$PluginPod.+\"})",
     "legendFormat": "Runtime"
    }
   ]
  },
  {
   "title": "Plugin Frequency by Image Type (All Time)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT plugins_plugin.dock_image AS \"Plugin\", \nCOUNT(*) AS \"Times Ran\"\nFROM plugininstances_plugininstance\nINNER JOIN plugins_plugin ON plugins_plugin.id = plugininstances_plugininstance.plugin_id\nWHERE plugininstances_plugininstance.status != 'cancelled'\nGROUP BY plugins_plugin.dock_image\nORDER BY COUNT(*) DESC"
    }
   ]
  },
  {
   "title": "Most Commonly Used Files (All Time)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n\tauth_user.username AS \"Username\",\n\tREGEXP_REPLACE(plugininstances_plugininstancefile.fname, '^.*/([^/]*?)(\\.[^/.]+)?$', '\\1') AS \"Filename\",\n\tCOUNT(*) AS \"Count\"\nFROM plugininstances_plugininstance\nINNER JOIN auth_user ON auth_user.id = plugininstances_plugininstance.owner_id\nINNER JOIN plugininstances_plugininstancefile ON plugininstances_plugininstancefile.plugin_inst_id = plugininstances_plugininstance.id\nGROUP BY auth_user.username, \"Filename\"\nHAVING COUNT(*) > 1\nORDER BY COUNT(*) DESC"
    }
   ]
  },
  {
   "title": "Plugins Exiting with Success vs. Failure by Week",
   "type": "timeseries",
   "description": "Counts the number of plugins that have returned a failure / success grouped by weeks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\nDATE_TRUNC('week', end_date) AS \"time\",\nCOUNT(*) AS \"finishedSuccessfully\"\nFROM plugininstances_plugininstance\nWHERE\nstatus = 'finishedSuccessfully'\nGROUP BY end_date"
    },
    {
     "rawSql": "SELECT\nDATE_TRUNC('week', end_date) AS \"time\",\nCOUNT(*) AS \"finishedWithError\"\nFROM plugininstances_plugininstance\nWHERE\nstatus = 'finishedWithError'\nGROUP BY end_date"
    }
   ]
  },
  {
   "title": "Overall Plugin Resource Use",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum (   pod:container_cpu_usage:sum{pod=~\"chris-jid-.+\"}   * on(namespace, pod) group_right(image_spec) kube_pod_container_info{} ) by(image)",
     "legendFormat": "{{image}}"
    },
    {
     "expr": "sum by(image) (container_memory_working_set_bytes{container=~\"chris-jid-.+\"}) / 1000000000",
     "legendFormat": "{{image}}"
    },
    {
     "expr": "avg by (image) (last_over_time(timestamp((kube_pod_start_time{}   * on(namespace, pod) group_right(image_spec) kube_pod_container_info{pod=~\"chris-jid.+\"}))[1w:]) -    (kube_pod_start_time{}   * on(namespace, pod) group_right(image_spec) kube_pod_container_info{pod=~\"chris-jid.+\"}))",
     "legendFormat": "{{image}}"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU Use by Pod (in CPU Use seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace='hosting-of-medical-image-analysis-platform-a88466'}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Use by Plugin Pods (in CPU Use seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by(pod) (pod:container_cpu_usage:sum{pod=~\"chris-jid-.+\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Use by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", namespace='hosting-of-medical-image-analysis-platform-a88466'}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Use by Plugin Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{pod=~\"chris-jid.+\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Filesystem Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(25, sort_desc(sum(pod:container_fs_usage_bytes:sum{container=\"\",pod!=\"\",namespace='hosting-of-medical-image-analysis-platform-a88466'}) BY (pod, namespace)))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Filesystem Use by Plugin Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(25, sort_desc(sum(pod:container_fs_usage_bytes:sum{container=\"\",pod=~\"chris-jid.+\",namespace='hosting-of-medical-image-analysis-platform-a88466'}) by (pod, namespace)))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "% of Total CPU and Memory Resources in Use",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", namespace=\"hosting-of-medical-image-analysis-platform-a88466\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"\", namespace=\"hosting-of-medical-image-analysis-platform-a88466\", resource=\"cpu\"})",
     "legendFormat": "% CPU Use (Limits)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", namespace=\"hosting-of-medical-image-analysis-platform-a88466\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"\", namespace=\"hosting-of-medical-image-analysis-platform-a88466\", resource=\"cpu\"})",
     "legendFormat": "% CPU Use (Requests)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"hosting-of-medical-image-analysis-platform-a88466\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"\", namespace=\"hosting-of-medical-image-analysis-platform-a88466\", resource=\"memory\"})",
     "legendFormat": "% Memory Use (Limits)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"hosting-of-medical-image-analysis-platform-a88466\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"\", namespace=\"hosting-of-medical-image-analysis-platform-a88466\", resource=\"memory\"})",
     "legendFormat": "% Memory Use (Requests)"
    }
   ]
  },
  {
   "title": "CPU Throttling Percentage by Plugin Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod) ((container_cpu_cfs_throttled_periods_total{pod=~\"chris-jid.+\", container=~\"chris-jid.+\"} / container_cpu_cfs_periods_total{pod=~\"chris-jid.+\", }))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "System Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Most Recent ChRIS Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "{pod=~\"chris.+\"} |= ``",
     "maxLines": 50
    }
   ]
  },
  {
   "title": "Plugin Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "{pod=~\"chris-jid.+\"}",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "Most Recent Plugin Errors",
   "type": "logs",
   "description": "Panel of all logs that follow the format that include an error code value",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "{pod=~\"chris.+\"} |~ \".+CODE.+\"",
     "maxLines": 200
    }
   ]
  }
 ]
}